const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT_DIR = path.resolve(__dirname, '..');
const DATA_DIR = path.join(ROOT_DIR, 'data');
const DB_FILE_BASE = path.join(DATA_DIR, 'sigac');
const DEMO_DOMAIN = '@demo.sigac.local';
const BASE_URL = process.env.SIGAC_BASE_URL || 'http://127.0.0.1:8080';

const ADMIN_CREDENTIALS = {
  email: 'admin@sigac.com',
  password: 'admin123',
};

const DEMO_CNPJS = [
  '31345678000190',
  '31456789000121',
  '31567890000154',
];

function log(message) {
  process.stdout.write(`${message}\n`);
}

function fail(message) {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

function sqlList(values) {
  return values.map((value) => `'${String(value).replace(/'/g, "''")}'`).join(', ');
}

function findH2Jar() {
  const h2Root = path.join(os.homedir(), '.m2', 'repository', 'com', 'h2database', 'h2');
  if (!fs.existsSync(h2Root)) {
    fail(`H2 não encontrado em ${h2Root}.`);
  }

  const versions = fs.readdirSync(h2Root)
    .filter((entry) => fs.statSync(path.join(h2Root, entry)).isDirectory())
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  for (let index = versions.length - 1; index >= 0; index -= 1) {
    const version = versions[index];
    const jarPath = path.join(h2Root, version, `h2-${version}.jar`);
    if (fs.existsSync(jarPath)) {
      return jarPath;
    }
  }

  fail('Não foi possível localizar o jar do H2 no repositório Maven local.');
}

function h2Url() {
  return `jdbc:h2:file:${DB_FILE_BASE};DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE`;
}

function schemaSql() {
  return `
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS condominios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  endereco VARCHAR(255),
  cnpj VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS gestores_condominio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condominio_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT uk_gestor_condominio UNIQUE (condominio_id, user_id)
);

CREATE TABLE IF NOT EXISTS sindicos_condominio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condominio_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT uk_sindico_condominio UNIQUE (condominio_id, user_id)
);

CREATE TABLE IF NOT EXISTS funcionarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  funcao VARCHAR(255) NOT NULL,
  valor_mensal DECIMAL(12, 2) NOT NULL,
  condominio_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS inquilinos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  condominio_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS gastos_produto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(500),
  valor DECIMAL(12, 2) NOT NULL,
  data DATE NOT NULL,
  loja_fornecedor VARCHAR(255),
  condominio_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS manutencoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(255) NOT NULL,
  valor DECIMAL(12, 2) NOT NULL,
  data DATE NOT NULL,
  tipo VARCHAR(30) NOT NULL,
  prestador VARCHAR(255),
  instrucoes_email VARCHAR(1000),
  condominio_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS arrecadacoes_mensais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano INT NOT NULL,
  mes INT NOT NULL,
  valor DECIMAL(12, 2) NOT NULL,
  condominio_id BIGINT NOT NULL,
  CONSTRAINT uk_arrecadacao_condominio_mes UNIQUE (condominio_id, ano, mes)
);

CREATE TABLE IF NOT EXISTS arrecadacao_mensal_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  arrecadacao_mensal_id BIGINT NOT NULL,
  alterado_em TIMESTAMP NOT NULL,
  user_id BIGINT,
  user_nome VARCHAR(200),
  user_email VARCHAR(200),
  valor_anterior DECIMAL(12, 2),
  valor_novo DECIMAL(12, 2) NOT NULL,
  acao VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS avisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(160) NOT NULL,
  mensagem VARCHAR(2000) NOT NULL,
  data_referencia DATE NOT NULL,
  origem VARCHAR(20) NOT NULL,
  alcance VARCHAR(20) NOT NULL,
  manutencao_id_origem BIGINT,
  criado_em TIMESTAMP NOT NULL,
  condominio_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS aviso_destinatarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aviso_id BIGINT NOT NULL,
  inquilino_id BIGINT,
  nome VARCHAR(160) NOT NULL,
  email VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS solicitacoes_manutencao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condominio_id BIGINT NOT NULL,
  titulo VARCHAR(500) NOT NULL,
  solicitante_id BIGINT NOT NULL,
  criado_em TIMESTAMP NOT NULL
);

MERGE INTO users (email, password, nome, role)
KEY(email)
VALUES (
  'admin@sigac.com',
  '$2a$10$UZgb3CtIFApLY3Sd3lh4deYgoVdM4BNRSs.sTfMhxR7SctwdgllWy',
  'SIGAC Admin',
  'SIGAC_ADMIN'
);
`;
}

function cleanupSql() {
  const cnpjs = sqlList(DEMO_CNPJS);
  const emailPattern = `%${DEMO_DOMAIN}`;

  return `
SET REFERENTIAL_INTEGRITY FALSE;

DELETE FROM aviso_destinatarios
WHERE aviso_id IN (
  SELECT id FROM avisos
  WHERE condominio_id IN (
    SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
  )
);

DELETE FROM avisos
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM arrecadacao_mensal_logs
WHERE arrecadacao_mensal_id IN (
  SELECT id FROM arrecadacoes_mensais
  WHERE condominio_id IN (
    SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
  )
);

DELETE FROM solicitacoes_manutencao
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM manutencoes
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM gastos_produto
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM funcionarios
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM inquilinos
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM arrecadacoes_mensais
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM gestores_condominio
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM sindicos_condominio
WHERE condominio_id IN (
  SELECT id FROM condominios WHERE cnpj IN (${cnpjs})
);

DELETE FROM condominios
WHERE cnpj IN (${cnpjs});

DELETE FROM users
WHERE email LIKE '${emailPattern}';

SET REFERENTIAL_INTEGRITY TRUE;
`;
}

function runSql(sql) {
  fs.mkdirSync(DATA_DIR, { recursive: true });

  const h2Jar = findH2Jar();
  const tempSqlFile = path.join(os.tmpdir(), `sigac-seed-${Date.now()}.sql`);
  fs.writeFileSync(tempSqlFile, sql, 'utf8');

  try {
    const result = spawnSync(
      'java',
      [
        '-cp',
        h2Jar,
        'org.h2.tools.RunScript',
        '-url',
        h2Url(),
        '-user',
        'sa',
        '-password',
        '',
        '-script',
        tempSqlFile,
      ],
      {
        cwd: ROOT_DIR,
        encoding: 'utf8',
      },
    );

    if (result.status !== 0) {
      const details = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
      fail(`Falha ao preparar o banco H2.\n${details}`);
    }
  } finally {
    fs.rmSync(tempSqlFile, { force: true });
  }
}

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function monthRef(offset) {
  const now = new Date();
  const shifted = new Date(now.getFullYear(), now.getMonth() + offset, 1);
  const year = shifted.getFullYear();
  const month = shifted.getMonth() + 1;

  return {
    year,
    month,
    date(day) {
      return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    },
  };
}

function buildDataset() {
  const current = monthRef(0);
  const previous = monthRef(-1);
  const twoMonthsAgo = monthRef(-2);

  return [
    {
      nome: 'Condomínio Serra do Curral',
      endereco: 'Rua Professor Estevão Pinto, 355 - Serra, Belo Horizonte - MG',
      cnpj: DEMO_CNPJS[0],
      gestor: {
        nome: 'Juliana Braga',
        email: `juliana.braga${DEMO_DOMAIN}`,
        password: 'gestor123',
      },
      sindico: {
        nome: 'Marcelo Campos',
        email: `marcelo.campos${DEMO_DOMAIN}`,
        password: 'sindico123',
      },
      funcionarios: [
        { nome: 'Carlos Henrique', funcao: 'Porteiro', valorMensal: 2850.0 },
        { nome: 'Rosângela Souza', funcao: 'Faxineira', valorMensal: 2320.0 },
        { nome: 'Edson Vieira', funcao: 'Zelador', valorMensal: 3480.0 },
      ],
      inquilinos: [
        { nome: 'Ana Luiza Duarte', email: `ana.duarte${DEMO_DOMAIN}` },
        { nome: 'Bruno Antunes', email: `bruno.antunes${DEMO_DOMAIN}` },
        { nome: 'Carla Menezes', email: `carla.menezes${DEMO_DOMAIN}` },
        { nome: 'Diego Faria', email: `diego.faria${DEMO_DOMAIN}` },
      ],
      arrecadacoes: [
        { ano: twoMonthsAgo.year, mes: twoMonthsAgo.month, valor: 46800.0 },
        { ano: previous.year, mes: previous.month, valor: 47250.0 },
        { ano: current.year, mes: current.month, valor: 47980.0 },
      ],
      gastos: [
        { descricao: 'Compra de materiais de limpeza para áreas comuns', valor: 648.5, data: current.date(3), lojaFornecedor: 'Apoio Mineiro - Cristiano Machado' },
        { descricao: 'Reposição de lâmpadas LED do hall e da garagem', valor: 384.9, data: current.date(11), lojaFornecedor: 'Leroy Merlin BH Norte' },
        { descricao: 'Bobinas e itens para portaria', valor: 196.4, data: current.date(19), lojaFornecedor: 'Papelaria Savassi' },
        { descricao: 'Produtos para jardinagem do canteiro frontal', valor: 289.3, data: previous.date(9), lojaFornecedor: 'Verde Minas Paisagismo' },
      ],
      manutencoes: [
        {
          descricao: 'Revisão preventiva do elevador social',
          valor: 1320.0,
          data: current.date(15),
          tipo: 'PREVISTA',
          prestador: 'Elevadores Atlas Schindler BH',
          instrucoesEmail: 'No horário da revisão, utilizar o elevador de serviço para mudanças e volumes maiores.',
        },
        {
          descricao: 'Reparo em vazamento da prumada do 6º andar',
          valor: 2480.0,
          data: previous.date(22),
          tipo: 'EMERGENCIAL',
          prestador: 'Hidro Minas Soluções',
          instrucoesEmail: 'Poderá haver interrupção momentânea da água entre 10h e 12h.',
        },
      ],
      avisos: [
        {
          titulo: 'Lavagem programada da garagem',
          mensagem: 'Na próxima sexta-feira, a garagem será lavada entre 8h e 12h. Pedimos a gentileza de retirar os veículos até 7h45.',
          dataReferencia: current.date(8),
          alcance: 'TODOS',
        },
        {
          titulo: 'Vistoria individual de hidrômetros',
          mensagem: 'A equipe de manutenção fará uma vistoria técnica nos hidrômetros das unidades 201 e 202. Favor garantir acesso aos apartamentos.',
          dataReferencia: current.date(18),
          alcance: 'ESPECIFICOS',
          destinatarios: ['Ana Luiza Duarte', 'Bruno Antunes'],
        },
      ],
      solicitacoes: [
        'Avaliar infiltração próxima ao shaft do 3º andar.',
        'Verificar ruído intermitente no portão da garagem.',
      ],
    },
    {
      nome: 'Edifício Mirante da Savassi',
      endereco: 'Rua Antônio de Albuquerque, 620 - Savassi, Belo Horizonte - MG',
      cnpj: DEMO_CNPJS[1],
      gestor: {
        nome: 'Rafael Teixeira',
        email: `rafael.teixeira${DEMO_DOMAIN}`,
        password: 'gestor123',
      },
      sindico: {
        nome: 'Renata Alves',
        email: `renata.alves${DEMO_DOMAIN}`,
        password: 'sindico123',
      },
      funcionarios: [
        { nome: 'Felipe Gonçalves', funcao: 'Porteiro', valorMensal: 2940.0 },
        { nome: 'Mariana Lopes', funcao: 'Auxiliar de Limpeza', valorMensal: 2390.0 },
        { nome: 'José Cláudio', funcao: 'Zelador', valorMensal: 3620.0 },
      ],
      inquilinos: [
        { nome: 'Fernanda Assis', email: `fernanda.assis${DEMO_DOMAIN}` },
        { nome: 'Gustavo Prado', email: `gustavo.prado${DEMO_DOMAIN}` },
        { nome: 'Helena Mattos', email: `helena.mattos${DEMO_DOMAIN}` },
        { nome: 'Igor Neves', email: `igor.neves${DEMO_DOMAIN}` },
      ],
      arrecadacoes: [
        { ano: twoMonthsAgo.year, mes: twoMonthsAgo.month, valor: 52340.0 },
        { ano: previous.year, mes: previous.month, valor: 52610.0 },
        { ano: current.year, mes: current.month, valor: 53180.0 },
      ],
      gastos: [
        { descricao: 'Reposição de insumos do espaço gourmet', valor: 512.4, data: current.date(5), lojaFornecedor: 'Supernosso Gourmet' },
        { descricao: 'Compra de toner e papel para administração', valor: 274.8, data: current.date(13), lojaFornecedor: 'Kalunga BH' },
        { descricao: 'Troca de sensores de presença dos corredores', valor: 836.2, data: previous.date(10), lojaFornecedor: 'Casa das Lâmpadas Savassi' },
        { descricao: 'Materiais para manutenção do jardim interno', valor: 318.6, data: current.date(21), lojaFornecedor: 'Flora Urbana BH' },
      ],
      manutencoes: [
        {
          descricao: 'Revisão do sistema de CFTV e gravação',
          valor: 1850.0,
          data: current.date(17),
          tipo: 'PREVISTA',
          prestador: 'Vision Segurança Eletrônica',
          instrucoesEmail: 'A equipe acessará a sala técnica e poderá testar câmeras nas áreas comuns.',
        },
        {
          descricao: 'Substituição da bomba de recalque da caixa superior',
          valor: 4210.0,
          data: previous.date(24),
          tipo: 'EMERGENCIAL',
          prestador: 'Hidro BH Engenharia',
          instrucoesEmail: 'Pode haver oscilação de pressão de água durante a execução do serviço.',
        },
      ],
      avisos: [
        {
          titulo: 'Assembleia ordinária do condomínio',
          mensagem: 'A assembleia ordinária será realizada no salão de festas, às 19h30, para apresentação de resultados e pauta de melhorias.',
          dataReferencia: current.date(12),
          alcance: 'TODOS',
        },
        {
          titulo: 'Acesso técnico ao shaft de internet',
          mensagem: 'As unidades 601 e 602 receberão a equipe de telecom para ajuste de cabeamento vertical. Favor manter alguém responsável no período da manhã.',
          dataReferencia: current.date(23),
          alcance: 'ESPECIFICOS',
          destinatarios: ['Fernanda Assis', 'Gustavo Prado'],
        },
      ],
      solicitacoes: [
        'Analisar vibração no exaustor da garagem.',
        'Avaliar regulagem do fechamento da porta corta-fogo no 11º andar.',
      ],
    },
    {
      nome: 'Residencial Pampulha Jardins',
      endereco: 'Avenida Fleming, 1480 - Ouro Preto, Belo Horizonte - MG',
      cnpj: DEMO_CNPJS[2],
      gestor: {
        nome: 'Larissa Mourão',
        email: `larissa.mourao${DEMO_DOMAIN}`,
        password: 'gestor123',
      },
      sindico: {
        nome: 'Tiago Nogueira',
        email: `tiago.nogueira${DEMO_DOMAIN}`,
        password: 'sindico123',
      },
      funcionarios: [
        { nome: 'Paulo César', funcao: 'Porteiro', valorMensal: 2810.0 },
        { nome: 'Mônica Ribeiro', funcao: 'Auxiliar de Serviços Gerais', valorMensal: 2280.0 },
        { nome: 'Sérgio Pacheco', funcao: 'Zelador', valorMensal: 3410.0 },
      ],
      inquilinos: [
        { nome: 'Jéssica Moura', email: `jessica.moura${DEMO_DOMAIN}` },
        { nome: 'Leonardo Paiva', email: `leonardo.paiva${DEMO_DOMAIN}` },
        { nome: 'Natália Rocha', email: `natalia.rocha${DEMO_DOMAIN}` },
        { nome: 'Otávio Diniz', email: `otavio.diniz${DEMO_DOMAIN}` },
      ],
      arrecadacoes: [
        { ano: twoMonthsAgo.year, mes: twoMonthsAgo.month, valor: 43890.0 },
        { ano: previous.year, mes: previous.month, valor: 44120.0 },
        { ano: current.year, mes: current.month, valor: 44680.0 },
      ],
      gastos: [
        { descricao: 'Compra de cloro e kits de teste para piscina', valor: 1186.0, data: current.date(4), lojaFornecedor: 'Pool Center Pampulha' },
        { descricao: 'Substituição de boias e registros do vestiário', valor: 402.7, data: previous.date(14), lojaFornecedor: 'Hidráulica Ouro Preto' },
        { descricao: 'Materiais para manutenção da churrasqueira', valor: 257.9, data: current.date(16), lojaFornecedor: 'Casa do Churrasqueiro BH' },
        { descricao: 'Itens de limpeza do salão de festas', valor: 219.5, data: current.date(24), lojaFornecedor: 'Mart Minas Castelo' },
      ],
      manutencoes: [
        {
          descricao: 'Limpeza técnica e regulagem do portão eletrônico',
          valor: 980.0,
          data: current.date(14),
          tipo: 'PREVISTA',
          prestador: 'EletroPort BH',
          instrucoesEmail: 'O acesso de veículos poderá operar em modo manual por até 40 minutos.',
        },
        {
          descricao: 'Reparo no aquecimento da piscina',
          valor: 3675.0,
          data: previous.date(20),
          tipo: 'EMERGENCIAL',
          prestador: 'Aqua Minas Assistência',
          instrucoesEmail: 'A piscina ficará interditada até a conclusão do ajuste técnico.',
        },
      ],
      avisos: [
        {
          titulo: 'Fechamento temporário da área da piscina',
          mensagem: 'A área da piscina permanecerá fechada para manutenção preventiva e reorganização do deck entre 9h e 15h.',
          dataReferencia: current.date(9),
          alcance: 'TODOS',
        },
        {
          titulo: 'Inspeção das unidades próximas à prumada da cobertura',
          mensagem: 'As unidades 801 e 802 receberão uma vistoria técnica de rotina relacionada à prumada hidráulica da cobertura.',
          dataReferencia: current.date(20),
          alcance: 'ESPECIFICOS',
          destinatarios: ['Jéssica Moura', 'Leonardo Paiva'],
        },
      ],
      solicitacoes: [
        'Solicitar avaliação da iluminação do playground.',
        'Verificar falha recorrente no interfone da torre B.',
      ],
    },
  ];
}

async function request(method, route, token, body) {
  const headers = { Accept: 'application/json' };
  if (body !== undefined) {
    headers['Content-Type'] = 'application/json';
  }
  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }

  let response;
  try {
    response = await fetch(`${BASE_URL}${route}`, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
      signal: AbortSignal.timeout(20000),
    });
  } catch (error) {
    throw new Error(`Falha de conexão em ${method} ${route}: ${error.message}`);
  }

  const raw = await response.text();
  let parsed = null;
  if (raw) {
    try {
      parsed = JSON.parse(raw);
    } catch {
      parsed = raw;
    }
  }

  if (!response.ok) {
    const detail = typeof parsed === 'string' ? parsed : JSON.stringify(parsed);
    throw new Error(`Erro HTTP ${response.status} em ${method} ${route}: ${detail}`);
  }

  return parsed;
}

async function login(email, password) {
  return request('POST', '/auth/login', null, { email, password });
}

async function seedCondominio(adminToken, entry) {
  const condominio = await request('POST', '/condominios', adminToken, {
    nome: entry.nome,
    endereco: entry.endereco,
    cnpj: entry.cnpj,
  });

  await request('POST', `/condominios/${condominio.id}/gestores`, adminToken, {
    nome: entry.gestor.nome,
    email: entry.gestor.email,
    password: entry.gestor.password,
    role: 'GESTOR',
  });

  await request('POST', `/condominios/${condominio.id}/sindicos`, adminToken, {
    nome: entry.sindico.nome,
    email: entry.sindico.email,
    password: entry.sindico.password,
    role: 'SINDICO',
  });

  const gestorAuth = await login(entry.gestor.email, entry.gestor.password);
  const sindicoAuth = await login(entry.sindico.email, entry.sindico.password);

  const inquilinos = [];
  for (const tenant of entry.inquilinos) {
    const created = await request('POST', `/condominios/${condominio.id}/inquilinos`, gestorAuth.token, tenant);
    inquilinos.push(created);
  }

  for (const employee of entry.funcionarios) {
    await request('POST', `/condominios/${condominio.id}/funcionarios`, gestorAuth.token, employee);
  }

  for (const arrecadacao of entry.arrecadacoes) {
    await request('PUT', `/condominios/${condominio.id}/arrecadacao-mensal`, gestorAuth.token, arrecadacao);
  }

  for (const gasto of entry.gastos) {
    await request('POST', `/condominios/${condominio.id}/gastos-produto`, gestorAuth.token, gasto);
  }

  const solicitacoesCriadas = [];
  for (const titulo of entry.solicitacoes) {
    const created = await request(
      'POST',
      `/condominios/${condominio.id}/solicitacoes-manutencao`,
      sindicoAuth.token,
      { titulo },
    );
    solicitacoesCriadas.push(created);
  }

  for (let index = 0; index < entry.manutencoes.length; index += 1) {
    const manutencao = { ...entry.manutencoes[index] };
    if (index === 0 && solicitacoesCriadas[0]) {
      manutencao.solicitacaoId = solicitacoesCriadas[0].id;
    }
    await request('POST', `/condominios/${condominio.id}/manutencoes`, gestorAuth.token, manutencao);
  }

  for (const aviso of entry.avisos) {
    const payload = {
      titulo: aviso.titulo,
      mensagem: aviso.mensagem,
      dataReferencia: aviso.dataReferencia,
      alcance: aviso.alcance,
    };

    if (aviso.alcance === 'ESPECIFICOS') {
      payload.destinatarios = aviso.destinatarios.map((nome) => {
        const tenant = inquilinos.find((item) => item.nome === nome);
        if (!tenant) {
          throw new Error(`Inquilino destinatário não encontrado para aviso específico: ${nome}`);
        }
        return {
          inquilinoId: tenant.id,
          nome: tenant.nome,
          email: tenant.email,
        };
      });
    }

    await request('POST', `/condominios/${condominio.id}/avisos`, gestorAuth.token, payload);
  }

  return {
    condominio,
    gestor: entry.gestor,
    sindico: entry.sindico,
    inquilinos: inquilinos.length,
    funcionarios: entry.funcionarios.length,
    gastos: entry.gastos.length,
    manutencoes: entry.manutencoes.length,
    avisos: entry.avisos.length,
    arrecadacoes: entry.arrecadacoes.length,
    solicitacoesPendentes: Math.max(solicitacoesCriadas.length - 1, 0),
  };
}

function printSummary(results) {
  const totals = results.reduce(
    (accumulator, item) => ({
      condominios: accumulator.condominios + 1,
      inquilinos: accumulator.inquilinos + item.inquilinos,
      funcionarios: accumulator.funcionarios + item.funcionarios,
      gastos: accumulator.gastos + item.gastos,
      manutencoes: accumulator.manutencoes + item.manutencoes,
      avisos: accumulator.avisos + item.avisos,
      arrecadacoes: accumulator.arrecadacoes + item.arrecadacoes,
      solicitacoesPendentes: accumulator.solicitacoesPendentes + item.solicitacoesPendentes,
    }),
    {
      condominios: 0,
      inquilinos: 0,
      funcionarios: 0,
      gastos: 0,
      manutencoes: 0,
      avisos: 0,
      arrecadacoes: 0,
      solicitacoesPendentes: 0,
    },
  );

  log('');
  log('Seed concluído com sucesso.');
  log(`Base HTTP: ${BASE_URL}`);
  log(`Condomínios criados: ${totals.condominios}`);
  log(`Gestores criados: ${totals.condominios}`);
  log(`Síndicos criados: ${totals.condominios}`);
  log(`Funcionários criados: ${totals.funcionarios}`);
  log(`Inquilinos criados: ${totals.inquilinos}`);
  log(`Gastos criados: ${totals.gastos}`);
  log(`Manutenções criadas: ${totals.manutencoes}`);
  log(`Avisos manuais criados: ${totals.avisos}`);
  log(`Arrecadações mensais definidas: ${totals.arrecadacoes}`);
  log(`Solicitações pendentes deixadas para demonstração: ${totals.solicitacoesPendentes}`);
  log('');
  log('Credenciais de demonstração:');
  log(`Admin: ${ADMIN_CREDENTIALS.email} / ${ADMIN_CREDENTIALS.password}`);
  log('Gestores:');
  for (const item of results) {
    log(`- ${item.condominio.nome}: ${item.gestor.email} / ${item.gestor.password}`);
  }
  log('Síndicos:');
  for (const item of results) {
    log(`- ${item.condominio.nome}: ${item.sindico.email} / ${item.sindico.password}`);
  }
}

async function main() {
  log('Preparando schema mínimo e limpando dataset demo anterior...');
  runSql(schemaSql());
  runSql(cleanupSql());

  log(`Validando acesso HTTP em ${BASE_URL}...`);
  const adminAuth = await login(ADMIN_CREDENTIALS.email, ADMIN_CREDENTIALS.password);
  if (!adminAuth || !adminAuth.token) {
    throw new Error('Login do admin não retornou token. Verifique se o backend já está rodando.');
  }

  const dataset = buildDataset();
  const results = [];

  for (const entry of dataset) {
    log(`Criando dados de demonstração para ${entry.nome}...`);
    results.push(await seedCondominio(adminAuth.token, entry));
  }

  printSummary(results);
}

main().catch((error) => {
  const detail = error && error.stack ? error.stack : String(error);
  fail(`Seed falhou.\n${detail}`);
});
